[wokwi]
version = 1
author = "Mohanad Sharif"
title = "Simple ADC LCD"
description = "ADC input from potentiometer displayed on I2C LCD1602"
board = "uno"
firmware = '../.pio/build/uno/firmware.hex'
elf = '../.pio/build/uno/firmware.elf'