[wokwi]
version = 1
author = "Mohanad Sharif"
title = "Simple Traffic Light"
description = "Traffic light controller simulation for Arduino Uno"
board = "uno"
firmware = '../.pio/build/uno/firmware.hex'
elf = '../.pio/build/uno/firmware.elf'